#!/usr/bin/env python3

import sys
import colorama
import subprocess as sp
import re

from colorama import Fore, Style

try:

	inFile1 = sys.argv[1]
	inFile2 = sys.argv[2]

	print('Starting!')
	print("")

	val1 = sp.getoutput('md5sum ' + inFile1)
	val2 = sp.getoutput('md5sum ' + inFile2)

	def getHash(input, sz=32):
		out = re.search(r'\b[0-9a-fA-F]{%d}\b' % sz, input).group(0)
		if out:
			return out

	print(getHash(val1))
	print(getHash(val2))
	print("")

	if getHash(val1) == getHash(val2):
		print(Fore.GREEN + 'md5 Hashes are the same!')
	else:
		print(Fore.RED + 'md5 Hashes do not match!')

except:
	print(Fore.RED + 'Please supply 2 files to compare!')